spring: #띄어쓰기 없음
#  datasource: #띄어쓰기 2칸
#    url: jdbc:h2:tcp://localhost/~/jpashop #4칸
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa: #띄어쓰기 2칸
#    hibernate: #띄어쓰기 4칸
#      ddl-auto: create #띄어쓰기 6칸
#    properties: #띄어쓰기 4칸
#      hibernate: #띄어쓰기 6칸
#        # show_sql: true #띄어쓰기 8칸
#        format_sql: true #띄어쓰기 8칸
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.213.215:3306/mysteryweb?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 362405
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: detectivesnight@gmail.com
    password: guohpyifuxzwefjn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

cloud:
  aws:
    s3:
      bucket: detectivesnight
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAZI2LGKUQGNCYS5EI
      secretKey: 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


